// <copyright file="CloudIDs.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
#if (UNITY_ANDROID || UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
    using Internal;
    using UnityEngine;
#endif
    /// <summary>
    /// Provides access to achievement- and leaderboard IDs registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudIDs
    {
        /// <summary>
        /// Contains properties that retrieves achievement IDs for the current platform.
        /// </summary>
        public static class AchievementIDs
        {
            public static string ArenaCleared
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQBw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_arenacleared_01";
#elif UNITY_EDITOR
                    return "ArenaCleared";
#else
                    return string.Empty;
#endif
                }
            }

            public static string DiamondCleared
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQCA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_diamondcleared_02";
#elif UNITY_EDITOR
                    return "DiamondCleared";
#else
                    return string.Empty;
#endif
                }
            }

            public static string OrbitCleared
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQCQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_orbitcleared_03";
#elif UNITY_EDITOR
                    return "OrbitCleared";
#else
                    return string.Empty;
#endif
                }
            }

            public static string PinballCleared
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQCg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_pinballcleared_04";
#elif UNITY_EDITOR
                    return "PinballCleared";
#else
                    return string.Empty;
#endif
                }
            }

            public static string WarpCleared
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQCw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_warpcleared_05";
#elif UNITY_EDITOR
                    return "WarpCleared";
#else
                    return string.Empty;
#endif
                }
            }

            public static string ClockCleared
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQDA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_clockcleared_06";
#elif UNITY_EDITOR
                    return "ClockCleared";
#else
                    return string.Empty;
#endif
                }
            }

            public static string TokenPlayer
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQDQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_tokenplayer_07";
#elif UNITY_EDITOR
                    return "TokenPlayer";
#else
                    return string.Empty;
#endif
                }
            }

            public static string StarPlayer
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQDg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_starplayer_08";
#elif UNITY_EDITOR
                    return "StarPlayer";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Capslider
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQDw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_capslider_09";
#elif UNITY_EDITOR
                    return "Capslider";
#else
                    return string.Empty;
#endif
                }
            }

            public static string ColorMeImpressed
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQEA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_colormeimpressed_10";
#elif UNITY_EDITOR
                    return "ColorMeImpressed";
#else
                    return string.Empty;
#endif
                }
            }
        }

        /// <summary>
        /// Contains properties that retrieves leaderboard IDs for the current platform.
        /// </summary>
        public static class LeaderboardIDs
        {
            public static string Arena
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQAA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_level1_arena";
#elif UNITY_EDITOR
                    return "Arena";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Diamond
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQAQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_level2_diamond";
#elif UNITY_EDITOR
                    return "Diamond";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Orbit
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQAg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_level3_orbit";
#elif UNITY_EDITOR
                    return "Orbit";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Pinball
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQAw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_level4_pinball";
#elif UNITY_EDITOR
                    return "Pinball";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Warp
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQBA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_level5_warp";
#elif UNITY_EDITOR
                    return "Warp";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Clock
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIm7Xjl_oXEAIQBQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "capslide_level6_clock";
#elif UNITY_EDITOR
                    return "Clock";
#else
                    return string.Empty;
#endif
                }
            }
        }
    }
}
